'use client';

import React from 'react';
import { Card, CardContent, CardHeader, CardTitle, Badge, SwissSubHeading, Button } from '@/components/ui/SwissUI';
import { Calendar, CheckCircle, Clock, Download } from 'lucide-react';
import { format } from 'date-fns';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface PlanViewerProps {
    plan: any;
}

export default function PlanViewer({ plan }: PlanViewerProps) {
    const { metrics, plan: schedule } = plan;

    const handleDownloadPDF = () => {
        const doc = new jsPDF();

        // 1. Header (Mimicking the Parul University Style)
        doc.setFontSize(22);
        doc.setTextColor(220, 38, 38); // Red color for 'University'
        doc.text("Parul University", 105, 20, { align: "center" });

        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);
        doc.text("Subject Syllabus", 200, 15, { align: "right" });
        doc.text("Generated via UAPS", 200, 20, { align: "right" });

        // Line separator
        doc.setLineWidth(0.5);
        doc.line(14, 25, 196, 25);

        // 2. Course Details
        doc.setFontSize(11);
        doc.text(`Course: Faculty Planner Generation`, 14, 35);
        doc.text(`Semester: N/A`, 160, 35);

        doc.text(`Prerequisite: Generated by AI`, 14, 42);

        // Course Objective (Mock/Static as we don't have this data yet)
        doc.setFontSize(10);
        doc.text("Course Objective:", 14, 50);
        const objective = "To effectively plan and distribute the curriculum topics across the available semester weeks, ensuring balanced workload and timely completion.";
        const splitObjective = doc.splitTextToSize(objective, 180);
        doc.text(splitObjective, 45, 50);

        // 3. Teaching Scheme Table (Mock based on metrics)
        doc.saveGraphicsState();
        doc.setFillColor(220, 220, 220);
        doc.rect(14, 60, 60, 8, 'F'); // Header background
        doc.rect(14, 60, 60, 8, 'S'); // Border
        doc.setFont('helvetica', 'bold');
        doc.text("Teaching Scheme", 16, 65);
        doc.restoreGraphicsState();

        autoTable(doc, {
            startY: 70,
            head: [['Lecture', 'Tutorial', 'Lab', 'Credit', 'Total Hours']],
            body: [[metrics.total_lectures, '0', '0', '4', metrics.total_lectures]],
            theme: 'grid',
            headStyles: { fillColor: [255, 255, 255], textColor: 0, lineWidth: 0.1 },
            styles: { fontSize: 10, halign: 'center', lineWidth: 0.1 },
            margin: { left: 14, right: 100 } // Keep it small
        });

        // 4. Course Content Table (The Main Plan)
        const contentStartY = (doc as any).lastAutoTable.finalY + 15;

        doc.saveGraphicsState();
        doc.setFillColor(200, 200, 200);
        doc.rect(14, contentStartY, 182, 8, 'F');
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.text("Course Content & Schedule", 16, contentStartY + 6);
        doc.restoreGraphicsState();

        // Prepare rows
        const rows: any[] = [];
        let srNo = 1;
        schedule.forEach((week: any) => {
            week.topics.forEach((topic: any) => {
                rows.push([
                    srNo++,
                    `Week ${week.week}: ${topic.title} ${topic.is_self_study ? '(Self Study)' : ''}`,
                    topic.duration_mins / 60, // Teaching Hours approx
                ]);
            });
        });

        autoTable(doc, {
            startY: contentStartY + 10,
            head: [['Sr.', 'Topics', 'Hours']],
            body: rows,
            theme: 'grid',
            headStyles: { fillColor: [255, 255, 255], textColor: 0, lineWidth: 0.1, fontStyle: 'bold' },
            columnStyles: {
                0: { cellWidth: 15, halign: 'center' },
                1: { cellWidth: 'auto' },
                2: { cellWidth: 20, halign: 'center' }
            },
            styles: { fontSize: 10, lineWidth: 0.1, lineColor: 0 },
        });

        // Footer
        const pageCount = (doc as any).internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.text(`Printed on : ${format(new Date(), 'dd-MM-yyyy HH:mm a')}`, 14, 290);
            doc.text(`Page ${i} of ${pageCount}`, 190, 290, { align: 'right' });
        }

        doc.save('academic_plan_syllabus.pdf');
    };

    return (
        <div className="space-y-8 animate-in fade-in slide-in-from-bottom-5 duration-500">

            {/* Action Bar */}
            <div className="flex justify-end">
                <Button onClick={handleDownloadPDF} className="bg-red-600 hover:bg-red-700 text-white">
                    <Download className="w-4 h-4 mr-2" />
                    Download Syllabus PDF
                </Button>
            </div>

            {/* Metrics Overview */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <Card className="bg-primary text-primary-foreground border-none">
                    <CardContent className="pt-6">
                        <div className="flex items-center justify-between mb-2">
                            <span className="text-primary-foreground/80 text-sm font-medium">Est. Completion</span>
                            <Calendar className="w-4 h-4 opacity-80" />
                        </div>
                        <div className="text-2xl font-bold">
                            {format(new Date(metrics.completion_date), 'MMM d, yyyy')}
                        </div>
                    </CardContent>
                </Card>

                <Card>
                    <CardContent className="pt-6">
                        <div className="flex items-center justify-between mb-2">
                            <span className="text-muted-foreground text-sm font-medium">Total Duration</span>
                            <Clock className="w-4 h-4 text-muted-foreground" />
                        </div>
                        <div className="text-2xl font-bold">
                            {metrics.total_weeks} <span className="text-sm font-normal text-muted-foreground">Weeks</span>
                        </div>
                    </CardContent>
                </Card>

                <Card>
                    <CardContent className="pt-6">
                        <div className="flex items-center justify-between mb-2">
                            <span className="text-muted-foreground text-sm font-medium">Contact Hours</span>
                            <CheckCircle className="w-4 h-4 text-muted-foreground" />
                        </div>
                        <div className="text-2xl font-bold">
                            {metrics.total_lectures} <span className="text-sm font-normal text-muted-foreground">Lectures</span>
                        </div>
                    </CardContent>
                </Card>
            </div>

            {/* Weekly Schedule */}
            <div className="space-y-6">
                <div className="flex items-center justify-between">
                    <h3 className="text-xl font-bold">Proposed Schedule</h3>
                </div>

                {schedule.map((week: any, idx: number) => (
                    <div key={idx} className="relative pl-8 border-l-2 border-border pb-8 last:pb-0 last:border-none">
                        <div className="absolute -left-[9px] top-0 w-4 h-4 rounded-full bg-background border-2 border-primary"></div>

                        <div className="mb-4">
                            <span className="text-xs font-bold uppercase tracking-wider text-primary mb-1 block">Week {week.week}</span>
                            <h4 className="text-lg font-bold">
                                {format(new Date(week.startDate), 'MMM d')} - {format(new Date(week.endDate), 'MMM d')}
                            </h4>
                        </div>

                        <div className="grid gap-3">
                            {week.topics.map((topic: any, tIdx: number) => (
                                <div key={tIdx} className="bg-card border rounded-md p-4 flex items-start justify-between group hover:border-primary/50 transition-colors">
                                    <div className="flex-1">
                                        <p className="font-medium text-sm text-foreground">{topic.title}</p>
                                        <div className="flex items-center gap-2 mt-2">
                                            {topic.is_self_study ? (
                                                <Badge variant="warning" className="text-[10px] px-1 py-0 h-5">Self Study</Badge>
                                            ) : (
                                                <Badge className="text-[10px] px-1 py-0 h-5 bg-slate-100 text-slate-700 hover:bg-slate-200 border-none">Lecture</Badge>
                                            )}
                                            <span className="text-xs text-muted-foreground flex items-center gap-1">
                                                <Clock className="w-3 h-3" /> {topic.duration_mins} mins
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            ))}
                            {week.topics.length === 0 && (
                                <div className="text-sm text-muted-foreground italic bg-muted/30 p-3 rounded">
                                    No regular lectures scheduled (Holiday or Recess).
                                </div>
                            )}
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
}
